apiVersion: 1

prune: true

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    editable: false
