create table sellers
(
    id                 bigint generated by default as identity primary key,
    external_seller_id varchar(100)             not null,
    seller_name        varchar(100)             not null,
    status             varchar(20)              not null,
    connected_at       timestamp with time zone not null,
    last_synced_at     timestamp with time zone null,
    created_at         timestamp with time zone not null default current_timestamp,
    updated_at         timestamp with time zone not null default current_timestamp
);

create unique index uk_sellers_external_seller_id
    on sellers (external_seller_id);