create table seller_credentials
(
    id                      bigint generated by default as identity primary key,
    seller_id               bigint                   not null,
    client_id               varchar(100)             not null,
    encrypted_client_secret text                     not null,
    client_secret_hint      varchar(4)               not null,
    created_at              timestamp with time zone not null default current_timestamp,
    updated_at              timestamp with time zone not null default current_timestamp,
    constraint fk_seller_credentials_seller_id
        foreign key (seller_id) references sellers (id)
);

create unique index uk_seller_credentials_seller_id
    on seller_credentials (seller_id);