create table import_jobs
(
    id                 bigint generated by default as identity primary key,
    seller_id          bigint                   not null,
    import_type        varchar(30)              not null,
    status             varchar(20)              not null,
    original_file_name varchar(255)             not null,
    total_row_count    integer                  not null default 0,
    success_row_count  integer                  not null default 0,
    failed_row_count   integer                  not null default 0,
    error_message      varchar(1000),
    started_at         timestamp with time zone,
    ended_at           timestamp with time zone,
    created_at         timestamp with time zone not null default current_timestamp,
    updated_at         timestamp with time zone not null default current_timestamp,
    constraint fk_import_jobs_seller_id
        foreign key (seller_id) references sellers (id)
);

create index idx_import_jobs_seller_id
    on import_jobs (seller_id);