create table products
(
    id                  bigint generated by default as identity primary key,
    seller_id           bigint                   not null,
    external_product_id varchar(100)             not null,
    product_name        varchar(255)             not null,
    sale_price          numeric(19, 2)           not null,
    stock_quantity      integer                  not null,
    product_status      varchar(50)              not null,
    created_at          timestamp with time zone not null default current_timestamp,
    updated_at          timestamp with time zone not null default current_timestamp,
    constraint fk_products_seller_id
        foreign key (seller_id) references sellers (id)
);

create unique index uk_products_seller_id_external_product_id
    on products (seller_id, external_product_id);

create table orders
(
    id                bigint generated by default as identity primary key,
    seller_id         bigint                   not null,
    external_order_no varchar(100)             not null,
    ordered_at        timestamp with time zone not null,
    order_status      varchar(50)              not null,
    total_amount      numeric(19, 2)           not null,
    created_at        timestamp with time zone not null default current_timestamp,
    updated_at        timestamp with time zone not null default current_timestamp,
    constraint fk_orders_seller_id
        foreign key (seller_id) references sellers (id)
);

create unique index uk_orders_seller_id_external_order_no
    on orders (seller_id, external_order_no);

create table order_items
(
    id                     bigint generated by default as identity primary key,
    order_id               bigint                   not null,
    product_id             bigint                   not null,
    external_order_item_no varchar(100)             not null,
    quantity               integer                  not null,
    unit_price             numeric(19, 2)           not null,
    item_amount            numeric(19, 2)           not null,
    created_at             timestamp with time zone not null default current_timestamp,
    updated_at             timestamp with time zone not null default current_timestamp,
    constraint fk_order_items_order_id
        foreign key (order_id) references orders (id),
    constraint fk_order_items_product_id
        foreign key (product_id) references products (id)
);

create unique index uk_order_items_order_id_external_order_item_no
    on order_items (order_id, external_order_item_no);