create table daily_metrics
(
    id                     bigint generated by default as identity primary key,
    seller_id              bigint                   not null,
    metric_date            date                     not null,
    order_count            integer                  not null,
    sales_amount           numeric(19, 2)           not null,
    average_order_amount   numeric(19, 2)           not null,
    sold_out_product_count integer                  not null,
    stale_product_count    integer                  not null,
    created_at             timestamp with time zone not null default current_timestamp,
    updated_at             timestamp with time zone not null default current_timestamp,
    constraint fk_daily_metrics_seller_id
        foreign key (seller_id) references sellers (id)
);

create unique index uk_daily_metrics_seller_id_metric_date
    on daily_metrics (seller_id, metric_date);