create table insights
(
    id            bigint generated by default as identity primary key,
    seller_id     bigint                   not null,
    metric_date   date                     not null,
    insight_type  varchar(50)              not null,
    severity      varchar(20)              not null,
    title         varchar(200)             not null,
    summary       varchar(1000)            not null,
    evidence_json text                     not null,
    generated_by  varchar(100)             not null,
    created_at    timestamp with time zone not null default current_timestamp,
    updated_at    timestamp with time zone not null default current_timestamp,
    constraint fk_insights_seller_id
        foreign key (seller_id) references sellers (id)
);

create unique index uk_insights_seller_id_metric_date_insight_type
    on insights (seller_id, metric_date, insight_type);

create index idx_insights_seller_id_metric_date
    on insights (seller_id, metric_date);