create table recommendations
(
    id             bigint generated by default as identity primary key,
    insight_id     bigint                   not null,
    priority       integer                  not null,
    action_code    varchar(100)             not null,
    action_title   varchar(200)             not null,
    action_message varchar(1000)            not null,
    source_rule    varchar(100)             not null,
    created_at     timestamp with time zone not null default current_timestamp,
    updated_at     timestamp with time zone not null default current_timestamp,
    constraint fk_recommendations_insight_id
        foreign key (insight_id) references insights (id)
);

create index idx_recommendations_insight_id
    on recommendations (insight_id);