create table pipeline_runs
(
    id                      bigint generated by default as identity primary key,
    pipeline_type           varchar(30)              not null,
    trigger_type            varchar(30)              not null,
    status                  varchar(30)              not null,
    metric_date             date                     not null,
    total_seller_count      integer                  not null,
    processed_seller_count  integer                  not null,
    failed_seller_count     integer                  not null,
    generated_insight_count integer                  not null,
    started_at              timestamp with time zone not null,
    ended_at                timestamp with time zone,
    created_at              timestamp with time zone not null default current_timestamp,
    updated_at              timestamp with time zone not null default current_timestamp
);

create index idx_pipeline_runs_type_metric_date
    on pipeline_runs (pipeline_type, metric_date);

create table pipeline_run_items
(
    id                      bigint generated by default as identity primary key,
    pipeline_run_id         bigint                   not null,
    seller_id               bigint                   not null,
    status                  varchar(20)              not null,
    generated_insight_count integer                  not null,
    error_message           varchar(1000),
    started_at              timestamp with time zone not null,
    ended_at                timestamp with time zone not null,
    created_at              timestamp with time zone not null default current_timestamp,
    updated_at              timestamp with time zone not null default current_timestamp,
    constraint fk_pipeline_run_items_pipeline_run_id
        foreign key (pipeline_run_id) references pipeline_runs (id),
    constraint fk_pipeline_run_items_seller_id
        foreign key (seller_id) references sellers (id)
);

create index idx_pipeline_run_items_pipeline_run_id
    on pipeline_run_items (pipeline_run_id);

create index idx_pipeline_run_items_seller_id
    on pipeline_run_items (seller_id);
