create table pipeline_execution_locks
(
    id            bigint generated by default as identity primary key,
    pipeline_type varchar(30)              not null,
    metric_date   date                     not null,
    created_at    timestamp with time zone not null default current_timestamp,
    updated_at    timestamp with time zone not null default current_timestamp
);

create unique index uk_pipeline_execution_locks_pipeline_type_metric_date
    on pipeline_execution_locks (pipeline_type, metric_date);